# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pulse_programmer - Copie.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import importlib
import numpy as np
import inspect
import sys
from pymodaq_plugins_pulsedmeasurement.utils import Config as PluginConfig

plugin_config = PluginConfig()

# Import all available pulse sequences from the path given in the plugin config file if any.
# If no path is given import them from the plugin resources.

if plugin_config("Extension", "sequences_path") != "":
    sys.path.append(
        "/".join(plugin_config("Extension", "sequences_path").split("/")[:-1])
    )
    pulse_sequences_module = importlib.import_module(
        plugin_config("Extension", "sequences_path").split("/")[-1]
    )
else:
    from pymodaq_plugins_pulsedmeasurement.resources import (
        default_pulse_sequences as pulse_sequences_module,
    )

from PyQt5 import QtCore, QtGui, QtWidgets
from decimal import Decimal
from pymodaq import Q_, Unit


class Ui_MainWindow(object):
    selected_sequence: str = None

    def setupUi(self, MainWindow):
        MainWindow.resize(826, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.layout_settings = QtWidgets.QHBoxLayout()
        self.layout_channel = QtWidgets.QVBoxLayout()
        self.label_channel = QtWidgets.QLabel(self.centralwidget)
        self.label_channel.setText("Channels")
        self.layout_channel.addWidget(self.label_channel)
        self.layout_channel_2 = QtWidgets.QHBoxLayout()
        self.layout_channel_IQ = QtWidgets.QVBoxLayout()
        self.param_channel_IQ = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_IQ.setFixedSize(QtCore.QSize(40, 20))
        self.param_channel_IQ.setValue(3)
        self.layout_channel_IQ.addWidget(self.param_channel_IQ)
        self.label_channel_IQ = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_IQ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_IQ.setText("IQ")
        self.layout_channel_IQ.addWidget(self.label_channel_IQ)
        self.layout_channel_2.addLayout(self.layout_channel_IQ)
        self.layout_channel_MW = QtWidgets.QVBoxLayout()
        self.param_channel_MW = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_MW.setFixedSize(QtCore.QSize(40, 20))
        self.param_channel_MW.setValue(2)
        self.layout_channel_MW.addWidget(self.param_channel_MW)
        self.label_channel_MW = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_MW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_MW.setText("MW")
        self.layout_channel_MW.addWidget(self.label_channel_MW)
        self.layout_channel_2.addLayout(self.layout_channel_MW)
        self.layout_channel_Laser = QtWidgets.QVBoxLayout()
        self.param_channel_Laser = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_Laser.setFixedSize(QtCore.QSize(40, 20))
        self.param_channel_Laser.setValue(1)
        self.layout_channel_Laser.addWidget(self.param_channel_Laser)
        self.label_channel_Laser = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_Laser.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_Laser.setText("Laser")
        self.layout_channel_Laser.addWidget(self.label_channel_Laser)
        self.layout_channel_2.addLayout(self.layout_channel_Laser)
        self.layout_channel_Counter = QtWidgets.QVBoxLayout()
        self.param_channel_Counter = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_Counter.setFixedSize(QtCore.QSize(40, 20))
        self.param_channel_Counter.setValue(0)
        self.layout_channel_Counter.addWidget(self.param_channel_Counter)
        self.label_channel_Counter = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_Counter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_Counter.setText("Counter")
        self.layout_channel_Counter.addWidget(self.label_channel_Counter)
        self.layout_channel_2.addLayout(self.layout_channel_Counter)
        self.layout_channel.addLayout(self.layout_channel_2)
        self.layout_settings.addLayout(self.layout_channel)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_settings.addItem(spacerItem)
        self.layout_general = QtWidgets.QVBoxLayout()
        self.label_general = QtWidgets.QLabel(self.centralwidget)
        self.label_general.setText("General Settings")
        self.layout_general.addWidget(self.label_general)
        self.layout_general_2 = QtWidgets.QHBoxLayout()
        self.layout_general_Rabi_period = QtWidgets.QVBoxLayout()
        self.param_general_Rabi_period = ScientificSpinBox(
            self.centralwidget,
            base_unit="ns",
            allowed_units=["ns", "us", "ms"],
            default_value=Decimal(20),
        )
        self.param_general_Rabi_period.setFixedSize(QtCore.QSize(80, 20))
        self.layout_general_Rabi_period.addWidget(self.param_general_Rabi_period)
        self.label_general_Rabi_period = QtWidgets.QLabel(self.centralwidget)
        self.label_general_Rabi_period.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_Rabi_period.setText("Rabi period")
        self.layout_general_Rabi_period.addWidget(self.label_general_Rabi_period)
        self.layout_general_2.addLayout(self.layout_general_Rabi_period)
        self.layout_general_MW_amplitude = QtWidgets.QVBoxLayout()
        self.param_general_MW_amplitude = ScientificSpinBox(
            self.centralwidget,
            base_unit="mV",
            allowed_units=["mV", "V"],
            default_value=Decimal(200),
        )
        self.param_general_MW_amplitude.setFixedSize(QtCore.QSize(80, 20))
        self.layout_general_MW_amplitude.addWidget(self.param_general_MW_amplitude)
        self.label_general_MW_amplitude = QtWidgets.QLabel(self.centralwidget)
        self.label_general_MW_amplitude.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_MW_amplitude.setText("MW amplitude")
        self.layout_general_MW_amplitude.addWidget(self.label_general_MW_amplitude)
        self.layout_general_2.addLayout(self.layout_general_MW_amplitude)
        self.layout_general_AOM_delay = QtWidgets.QVBoxLayout()
        self.param_general_AOM_delay = ScientificSpinBox(
            self.centralwidget,
            base_unit="ns",
            allowed_units=["ns", "us", "ms"],
            default_value=Decimal(390),
        )
        self.param_general_AOM_delay.setFixedSize(QtCore.QSize(80, 20))
        self.layout_general_AOM_delay.addWidget(self.param_general_AOM_delay)
        self.label_general_AOM_delay = QtWidgets.QLabel(self.centralwidget)
        self.label_general_AOM_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_AOM_delay.setText("AOM delay")
        self.layout_general_AOM_delay.addWidget(self.label_general_AOM_delay)
        self.layout_general_2.addLayout(self.layout_general_AOM_delay)
        self.layout_general_Final_wait = QtWidgets.QVBoxLayout()
        self.param_general_Final_wait = ScientificSpinBox(
            self.centralwidget,
            base_unit="ns",
            allowed_units=["ns", "us", "ms", "s"],
            default_value=Decimal(1000),
        )
        self.param_general_Final_wait.setFixedSize(QtCore.QSize(80, 20))
        self.layout_general_Final_wait.addWidget(self.param_general_Final_wait)
        self.label_general_Final_wait = QtWidgets.QLabel(self.centralwidget)
        self.label_general_Final_wait.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_Final_wait.setText("Final wait")
        self.layout_general_Final_wait.addWidget(self.label_general_Final_wait)
        self.layout_general_2.addLayout(self.layout_general_Final_wait)
        self.layout_general_Binwidth = QtWidgets.QVBoxLayout()
        self.param_general_Binwidth = QtWidgets.QComboBox(self.centralwidget)
        self.param_general_Binwidth.setFixedSize(QtCore.QSize(80, 20))
        self.layout_general_Binwidth.addWidget(self.param_general_Binwidth)
        self.label_general_Binwidth = QtWidgets.QLabel(self.centralwidget)
        self.label_general_Binwidth.setAlignment(QtCore.Qt.AlignCenter)
        for bin in 200e-12 * 2 ** np.arange(1, 20):
            self.param_general_Binwidth.addItem(f"{bin:.2e} s")
        self.label_general_Binwidth.setText("Binwidth")
        self.layout_general_Binwidth.addWidget(self.label_general_Binwidth)
        self.layout_general_2.addLayout(self.layout_general_Binwidth)
        self.layout_general.addLayout(self.layout_general_2)
        self.layout_settings.addLayout(self.layout_general)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_settings.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_settings)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_parameters = QtWidgets.QWidget()
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_parameters)
        self.layout_add_sequence = QtWidgets.QHBoxLayout()
        self.comboBox_list_sequence = QtWidgets.QComboBox(self.tab_parameters)
        for seq in [
            obj for obj in dir(pulse_sequences_module) if obj.startswith("Sequence_")
        ]:
            seq = "_".join(map(str, seq.split("_")[1:]))
            self.comboBox_list_sequence.addItem(seq)
        self.layout_add_sequence.addWidget(self.comboBox_list_sequence)
        self.button_add_sequence = QtWidgets.QPushButton(self.tab_parameters)
        self.button_add_sequence.setText("Add")
        self.button_add_sequence.clicked.connect(
            lambda: self.add_sequence(self.comboBox_list_sequence.currentText())
        )
        self.layout_add_sequence.addWidget(self.button_add_sequence)
        self.text_selected_seq = QtWidgets.QLabel(self.tab_parameters)
        self.text_selected_seq.setText("Selected sequence:")
        self.layout_add_sequence.addWidget(self.text_selected_seq)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_add_sequence.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.layout_add_sequence)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.formLayout.setVerticalSpacing(10)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_4.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_parameters, "")
        self.tab_plot = QtWidgets.QWidget()
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_plot)
        self.button_program = QtWidgets.QPushButton(self.tab_plot)
        self.button_program.setMaximumSize(QtCore.QSize(80, 30))
        self.button_program.setText("Program")
        self.verticalLayout_5.addWidget(self.button_program)
        self.plot_program = PlotWidget(self.tab_plot)
        self.verticalLayout_5.addWidget(self.plot_program)
        self.tabWidget.addTab(self.tab_plot, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_parameters),
            _translate("MainWindow", "Parameters"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_plot), _translate("MainWindow", "Program")
        )

    def add_sequence(self, name):
        """
        Add the sequence choosen with the combo box to the GUI and create all its parameter widgets.
        """
        ########################################
        # Parse the sequence specific parameters
        ########################################
        params_dict = {}
        attributes = [
            attr
            for attr in inspect.getmembers(
                getattr(pulse_sequences_module, f"Sequence_{name}"),
                lambda a: not inspect.isroutine(a),
            )
            if not (attr[0].startswith("__") and attr[0].endswith("__"))
        ]
        for quantity_name, quantity_value in attributes:
            if quantity_name.startswith("gui_"):
                params_dict["_".join(map(str, quantity_name.split("_")[1:]))] = (
                    quantity_value
                )

        ############################################################
        # Create the sequence widget and add them to the form layout
        ############################################################
        count = self.formLayout.rowCount()
        # Set the form label to the equence name
        self.__dict__[f"label_{name}_name"] = QtWidgets.QLabel(self.tab_parameters)
        self.__dict__[f"label_{name}_name"].setAlignment(QtCore.Qt.AlignCenter)
        # self.__dict__[f"label_{name}_name"].setObjectName(f"label_{name}_name")
        self.__dict__[f"label_{name}_name"].setText(name)
        self.formLayout.setWidget(
            count, QtWidgets.QFormLayout.LabelRole, self.__dict__[f"label_{name}_name"]
        )
        # Create the layout for thhe parameters widgets
        self.__dict__[f"layout_{name}"] = QtWidgets.QHBoxLayout()
        # self.__dict__[f"layout_{name}"].setObjectName(f"layout_{name}")
        self.__dict__[f"layout_{name}"].setSpacing(6)
        # Create the Select/Remove buttons
        self.__dict__[f"layout_{name}_select"] = QtWidgets.QVBoxLayout()
        # self.__dict__[f"layout_{name}_select"].setObjectName(f"layout_{name}_select")
        self.__dict__[f"button_{name}_select"] = QtWidgets.QPushButton(
            self.tab_parameters
        )
        self.__dict__[f"button_{name}_select"].setMaximumSize(
            QtCore.QSize(80, 16777215)
        )
        # self.__dict__[f"button_{name}_select"].setObjectName(f"button_{name}_select")
        self.__dict__[f"button_{name}_select"].setText("Select")
        self.__dict__[f"layout_{name}_select"].addWidget(
            self.__dict__[f"button_{name}_select"]
        )
        self.__dict__[f"button_{name}_remove"] = QtWidgets.QPushButton(
            self.tab_parameters
        )
        # self.__dict__[f"button_{name}_remove"].setObjectName(f"button_{name}_remove")
        self.__dict__[f"button_{name}_remove"].setText("Remove")
        self.__dict__[f"layout_{name}_select"].addWidget(
            self.__dict__[f"button_{name}_remove"]
        )
        self.__dict__[f"layout_{name}"].addLayout(
            self.__dict__[f"layout_{name}_select"]
        )
        # Create the widgets for the parameters
        for q_name, q_value in params_dict.items():
            # make the layout for the parameter widgets
            self.__dict__[f"layout_{name}_{q_name}"] = QtWidgets.QVBoxLayout()
            # make the spinbox and label widgets
            if type(q_value) == int:
                self.__dict__[f"param_{name}_{q_name}"] = QtWidgets.QSpinBox(
                    self.tab_parameters
                )
                self.__dict__[f"param_{name}_{q_name}"].setValue(q_value)
            else:
                base_unit = format(q_value.units, "~")
                allowed_units = [
                    format(unit, "~") for unit in get_allowed_units(q_value.units)
                ]
                self.__dict__[f"param_{name}_{q_name}"] = ScientificSpinBox(
                    self.tab_parameters,
                    base_unit=base_unit,
                    allowed_units=allowed_units,
                )
                self.__dict__[f"param_{name}_{q_name}"].setValue(q_value.magnitude)
            self.__dict__[f"param_{name}_{q_name}"].setMinimumSize(QtCore.QSize(80, 0))
            self.__dict__[f"layout_{name}_{q_name}"].addWidget(
                self.__dict__[f"param_{name}_{q_name}"]
            )
            self.__dict__[f"label_{name}_{q_name}"] = QtWidgets.QLabel(
                self.tab_parameters
            )
            self.__dict__[f"label_{name}_{q_name}"].setMinimumSize(QtCore.QSize(0, 0))
            self.__dict__[f"label_{name}_{q_name}"].setMaximumSize(
                QtCore.QSize(16777215, 15)
            )
            self.__dict__[f"label_{name}_{q_name}"].setAlignment(QtCore.Qt.AlignCenter)
            # self.__dict__[f"label_{name}_{p}"].setObjectName(f"label_{name}_{p}")
            self.__dict__[f"label_{name}_{q_name}"].setText(
                " ".join(map(str, q_name.split("_")))
            )  # we replace the _ with spaces for the parameter names in the gui
            self.__dict__[f"layout_{name}_{q_name}"].addWidget(
                self.__dict__[f"label_{name}_{q_name}"]
            )
            self.__dict__[f"layout_{name}"].addLayout(
                self.__dict__[f"layout_{name}_{q_name}"]
            )
        # add the spacer to keep thing on the left
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.__dict__[f"layout_{name}"].addItem(spacerItem)
        self.formLayout.setLayout(
            count, QtWidgets.QFormLayout.FieldRole, self.__dict__[f"layout_{name}"]
        )

        #######################################
        # Connect the Select and Remove buttons
        #######################################
        self.__dict__[f"button_{name}_select"].clicked.connect(
            lambda: self.select_sequence(name)
        )
        self.__dict__[f"button_{name}_remove"].clicked.connect(
            lambda: self.remove_sequence(name)
        )

    def remove_sequence(self, name):
        """
        Remove a given sequence.
        """
        seq_label = self.formLayout.labelForField(self.__dict__[f"layout_{name}"])
        if seq_label is not None:
            seq_label.deleteLater()
        deleteItems(self.__dict__[f"layout_{name}"])
        self.__dict__[f"layout_{name}"].deleteLater()

    def select_sequence(self, name):
        """
        Select a given sequence (which will then be used to progra the pulseblaster).
        """
        self.selected_sequence = name
        self.text_selected_seq.setText(f"Selected sequence: {name}")


def deleteItems(layout):
    """
    Function to recursively delete the widgets in a given layout.
    """
    if layout is not None:
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()
            else:
                deleteItems(item.layout())


def get_allowed_units(unit):
    """
    Return the allowed units in the Scientific Spin Boxes from the given unit as a list.
    """
    prefixes = ["nano", "micro", "milli", "", "kilo", "mega", "giga"]
    base_units = ["second", "volt", "hertz"]
    for base_unit in base_units:
        allowed_units = [Unit(pref + base_unit) for pref in prefixes]
        if unit in allowed_units:
            return allowed_units
    allowed_units = [base_unit]
    return allowed_units


from pyqtgraph import PlotWidget
from scientific_spinbox.widget import ScientificSpinBox


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
